# Generated by Django 6.0.5 on 2026-06-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ဘာသာရပ်အမည်')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='သင်ခန်းစာခေါင်းစဉ်')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='သင်ခန်းစာအကျဉ်းချုပ်')),
                ('content', models.TextField(verbose_name='သင်ခန်းစာအကြောင်းအရာ')),
                ('video_material', models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='ဗီဒီယိုမီဒီယာ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lessons/attachments/', verbose_name='ပူးတွဲဖိုင်တွဲများ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ဖန်တီးသည့်နေ့ရက်')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='Education.course', verbose_name='ဘာသာရပ်')),
            ],
            options={
                'verbose_name': 'သင်ခန်းစာ',
                'verbose_name_plural': 'သင်ခန်းစာများ',
                'ordering': ['-created_at'],
            },
        ),
    ]
