# Generated by Django 6.0.5 on 2026-06-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at']},
        ),
    ]
