# Generated by Django 6.0.5 on 2026-06-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/images/', verbose_name='သင်ခန်းစာပုံ'),
        ),
    ]
