# Generated by Django 6.0.5 on 2026-07-05 19:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='သင်ခန်းစာအကြောင်းအရာ'),
        ),
    ]
